ignores:
  - "sass-loader"
  - "bootstrap"
  - "@vue/cli-plugin-eslint"
  - "babel-eslint"
  - "@vue/cli-plugin-babel"
  - "browserslist"
  - "vue-loader"
  - "vue3-gettext"
  - "@vue/eslint-config-airbnb"
  - "eslint-config-prettier"
  - "eslint-plugin-import"
  - "eslint-plugin-prettier"
  - "eslint-plugin-prettier-vue"
  - "prettier"
  - "sass"
specials:
  - "bin"
  - "eslint"
skip-missing: true
